# Generated by Django 4.2 on 2023-05-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_alter_purpose_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='purpose',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
